'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, Check, ChevronDown, Sparkles, Stethoscope } from 'lucide-react'
import { ProcessingLoader } from './processing-loader'
import { CtaButton } from './cta-button'

const PASO2_STEPS = ['Analizando tu perfil de equilibrio', 'Seleccionando tu oferta personalizada', 'Reservando tu acceso exclusivo']
const pillars = [
  ['01', 'Evaluación inicial inteligente', 'La IA hace una evaluación rápida y personalizada: dónde duele, desde cuándo, si es ardor, hormigueo o descargas, intensidad del 0 al 10, si afecta el equilibrio. Con eso crea tu perfil único de síntomas y empieza a rastrear cada cambio. Ya no es “creo que empeoró”. Son datos reales sobre ti.'],
  ['02', 'Mapa + checklist diario de los pies', 'Registras visualmente dónde duele, arde u hormiguea cada día. La IA convierte esto en una línea de tiempo clara. En vez de “creo que estoy empeorando”, ves: “El hormigueo bajó de 7/10 a 3/10 en 7 días.” Todo en una sola pantalla — dolor, ardor, entumecimiento, sueño y equilibrio.'],
  ['03', 'NeuroAssist 24h', 'Son las 3 de la mañana y algo en el pie te preocupa. Un botón: “Estoy sintiendo esto ahora.” La IA te orienta al instante con medidas seguras de autocuidado — sin pánico, sin Google, sin esperar al día siguiente. No receta ni promete: solo te dice qué hacer ahora.'],
  ['04', 'Detector de señales de alerta', 'La IA vigila constantemente tus registros. Si aparece algo preocupante —herida abierta, hinchazón, pérdida de sensibilidad— te lo dice sin rodeos: “Esto necesita una evaluación médica.” Sin minimizar. Sin confundir. Cuando importa, la app te lo señala claro.'],
  ['05', 'Análisis visual de los pies con IA', 'Tomas una foto y la IA detecta posibles alteraciones: heridas, enrojecimiento, hinchazón, asimetrías. No diagnostica. En vez de “tienes una infección”, dice: “Se observa enrojecimiento. Si persiste, busca evaluación médica.” Es orientación visual, no diagnóstico — te ayuda a saber cuándo algo merece atención.'],
]
const bonuses = [
  ['Guía Familiar: Cómo Hablar de tu Neuropatía sin Perder tu Independencia', 'Una guía práctica para explicar tus síntomas, límites y necesidades a tu familia sin sentirte una carga — y aprender a pedir ayuda cuando realmente la necesitas, manteniendo al mismo tiempo tu autonomía y tu dignidad.', 'US$27'],
  ['Guía de Intimidad y Conexión Sexual', 'Una guía privada y sencilla sobre disfunción eréctil, salud de la próstata, libido femenina y lubricación, para entender mejor lo que está pasando en tu cuerpo, recuperar la confianza y mantener viva la conexión sexual con tu pareja, sin vergüenza ni secretos.', 'US$27'],
  ['Plan Financiero de tu Cuidado', 'Una herramienta práctica para organizar medicamentos, consultas, estudios y otros gastos relacionados con tu salud — para saber exactamente cuánto estás gastando, anticipar los próximos gastos y evitar que tu proceso de cuidado se convierta en un desorden financiero.', 'US$27'],
  ['Guía Anti-Constreñimiento: El Cuidado Estético de tus Pies', 'Una guía práctica para cuidar la apariencia de tus pies cuando aparecen problemas como piel seca y escamada, uñas engrosadas y deformaciones visibles — ayudándote a establecer una rutina de cuidado e higiene para sentirte más cómodo y seguro al mostrar tus pies.', 'US$27'],
  ['El Miedo Silencioso a la Demencia: Guía para Reconocer las Señales y Cómo Prevenirla', 'Descubre qué cambios en la memoria, la atención y el comportamiento merecen una evaluación profesional — y cuáles no — para dejar de preguntarte en silencio: “¿Y si esto es demencia?” y cómo prevenir la demencia de forma efectiva.', 'US$17'],
  ['7 Medicamentos que Pueden Afectar Mucho tus Nervios', 'Una guía práctica para conocer 7 medicamentos utilizados para otras condiciones de salud que pueden agravar considerablemente el daño nervioso, las alteraciones de la sensibilidad o el empeoramiento de determinados síntomas en algunas personas.', 'US$17'],
]
const faqs = [
  ['¿Puedo comprarlo después?', 'Esta condición especial está disponible únicamente en esta página. Si cierras esta página, esta oferta no volverá a aparecer.'],
  ['¿Por qué necesito esto si ya tengo los dos protocolos?', 'Porque cumplen funciones diferentes. Un protocolo trabaja tus molestias, otro trabaja movilidad y equilibrio, y la Dieta Japonesa organiza tus hábitos. El Médico Virtual añade un punto de apoyo digital para acompañar tu recorrido.'],
  ['¿Por qué cuesta solamente US$97 con tantos bonos y funcionalidades?', 'Es una condición especial creada como complemento para las personas que ya adquirieron el Método de la Dieta Japonesa.'],
  ['¿Necesito saber usar tecnología?', 'No. Solo necesitas acceder desde tu dispositivo y seguir indicaciones claras, sin conocimientos técnicos avanzados.'],
  ['¿Es difícil utilizarlo?', 'No. Todo está organizado de forma práctica para consultar información, resolver dudas y utilizar las herramientas cuando las necesites.'],
  ['¿Y si no es adecuado para mí?', 'Tienes una garantía de satisfacción de 7 días. Puedes revisar el material y solicitar el reembolso inmediato si no es adecuado para ti.'],
]

function Section({ children, className = '', id }: { children: React.ReactNode; className?: string; id?: string }) {
  return <section id={id} className={`mx-auto w-full max-w-2xl px-5 py-9 sm:py-14 ${className}`}>{children}</section>
}

function PrimaryCta({ children, scrollTo = 'oferta' }: { children: React.ReactNode; scrollTo?: string }) {
  return <CtaButton scrollTo={scrollTo} className="min-h-11 w-full rounded-xl px-4 py-2.5 text-[13px] font-extrabold uppercase leading-tight shadow-[0_12px_28px_-12px_var(--primary)] sm:min-h-14 sm:rounded-2xl sm:px-5 sm:text-base">{children}</CtaButton>
}

export function OtoExperience() {
  const [ready, setReady] = useState(false)
  const [ready2, setReady2] = useState(false)
  const revealed = ready && ready2
  useEffect(() => { if (revealed) window.scrollTo({ top: 0, behavior: 'auto' }) }, [revealed])

  return <>
    {!ready && <ProcessingLoader onDone={() => setReady(true)} />}
    {ready && !ready2 && <ProcessingLoader onDone={() => setReady2(true)} badge="Paso 2 de 3" title="Preparando tu oferta" subtitle="No cierres esta página mientras personalizamos tu oferta." steps={PASO2_STEPS} duration={15000} />}
    <main className={`bg-background text-foreground transition-opacity duration-700 ${revealed ? 'opacity-100' : 'pointer-events-none opacity-0'}`} aria-hidden={!revealed}>
      <div id="pagina">
        <section className="relative overflow-hidden border-b border-primary/25 px-5 pb-16 pt-10 text-center sm:pt-20">
          <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,color-mix(in_oklch,var(--primary)_25%,transparent),transparent_65%)]" />
          <div className="mx-auto max-w-2xl">
            <span className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary"><Stethoscope className="size-3.5" /> Tu nuevo punto de apoyo</span>
            <h1 className="mt-6 text-balance font-display text-3xl font-extrabold uppercase leading-[1.04] tracking-tight sm:text-5xl">Tu Médico Virtual <span className="text-primary">24H</span>: resuelve tu duda urgente de neuropatía al instante</h1>
            <p className="mx-auto mt-5 max-w-xl text-pretty text-sm leading-6 text-muted-foreground sm:text-base">Herramienta de última generación que te conecta al instante con tu Médico Virtual de IA especializado en neuropatía, disponible 24h — para cuando tienes una duda urgente y no puedes esperar días por una cita.</p>
            <img src="/images/medical-ai-mockup.png" alt="Tu Médico Virtual 24H en un teléfono móvil" className="mx-auto mt-9 w-full max-w-[440px] rounded-2xl border border-primary/25 shadow-[0_0_80px_-20px_var(--primary)]" />
<div className="mt-7"><PrimaryCta>Quiero mi Médico Virtual 24H</PrimaryCta></div>
          </div>
        </section>

        <Section className="text-center"><Sparkles className="mx-auto size-7 text-primary" /><p className="mt-4 text-xs font-bold uppercase tracking-[0.18em] text-primary">¡Felicidades!</p><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Acabas de garantizar tu acceso al Método de la Dieta Japonesa de 14 Días</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-muted-foreground">Ahora ya cuentas con una base para trabajar: alimentación, hábitos diarios, una rutina completa y la observación consciente de tus pies.</p><div className="mx-auto mt-8 max-w-xl rounded-2xl border border-primary/20 bg-card p-5 text-left"><p className="font-display text-sm font-extrabold uppercase text-primary">Ya tienes un material importante en tus manos.</p><div className="mt-4 space-y-3 text-sm leading-6 text-muted-foreground"><p>Pero existe una dificultad que muchas personas solo descubren después.</p><p>Puedes tener los mejores materiales, buscar en Google cada síntoma, ver decenas de videos de neurólogos y entrar en grupos y foros buscando a alguien que entienda lo que sientes.</p><p>Y, aun así, seguirás sin recibir una orientación correcta y profesional de acuerdo con esa duda específica que es solo tuya.</p><p className="font-display font-extrabold text-foreground">Tener información no es lo mismo que tener una herramienta de última generación, especializada en neuropatía y disponible para ti las 24 horas del día.</p><p className="font-display font-extrabold text-primary">Y exactamente ahí comienza el siguiente nivel.</p></div></div></Section>

        <Section className="border-y border-border/60"><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">La diferencia entre tener información y tener un punto de apoyo</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><h3 className="font-display font-extrabold uppercase text-muted-foreground">❌ Tener varios protocolos</h3><div className="mt-4 space-y-2 text-sm leading-6 text-muted-foreground"><p>Lees contenido.</p><p>Intentas recordar cada recomendación que ya escuchaste.</p><p>Preguntas a familiares.</p><p>Abres varios PDF.</p><p>Buscas entre decenas de páginas en Internet.</p><p>Intentas recordar dónde estaba aquella explicación exacta.</p><p className="pt-2 font-display font-extrabold text-foreground">Y terminas haciendo exactamente lo que querías evitar: perder mucho tiempo resolviéndolo todo por tu cuenta — y al final, encontrar una respuesta genérica que no resuelve tu duda específica.</p></div></div><div className="rounded-2xl border border-primary/50 bg-primary/10 p-5 shadow-[0_0_40px_-18px_var(--primary)]"><h3 className="font-display font-extrabold uppercase text-primary">🏆 Y TENER UN MÉDICO VIRTUAL 24H ESPECIALIZADO EN NEUROPATÍA DENTRO DE TU PROCESO</h3><p className="mt-4 text-sm leading-6">En lugar de depender únicamente de materiales aislados, tendrás un acompañamiento digital disponible las 24 horas del día para resolver tus dudas al instante, recibir orientación clara y profesional durante tu recorrido, y entender exactamente qué hacer — sin esperar días, sin depender de tu memoria y sin buscar entre páginas en Internet.</p></div></div></Section>

        <Section><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">5 pilares de la aplicación</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{pillars.map(([number, title, description]) => <article key={number} className="group rounded-2xl border border-border bg-card p-4 transition-all hover:-translate-y-0.5 hover:border-primary/60 hover:shadow-[0_16px_35px_-24px_var(--primary)] sm:p-5"><div className="flex items-start gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 font-mono text-xs font-bold text-primary">{number}</span><div><h3 className="text-pretty font-display text-[13px] font-extrabold uppercase leading-5">{title}</h3><p className="mt-2 text-[13px] leading-5 text-muted-foreground">{description}</p></div></div></article>)}</div></Section>

        <Section><div className="rounded-3xl border border-primary/35 bg-primary/5 p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="font-display text-[10px] font-bold uppercase tracking-[0.18em] text-primary">Incluidos con tu acceso</p><h2 className="mt-1 font-display text-2xl font-extrabold uppercase leading-none sm:text-4xl">6 bonos exclusivos</h2></div><span className="shrink-0 rounded-full bg-primary px-3 py-1.5 font-display text-xs font-extrabold text-primary-foreground">US$142</span></div><div className="mt-5 grid gap-2">{bonuses.map(([title, , value], index) => <article key={title} className="flex items-center gap-3 rounded-2xl border border-border bg-card px-3 py-2.5"><span className="flex size-6 shrink-0 items-center justify-center rounded-md bg-primary/10 font-mono text-[10px] font-bold text-primary">0{index + 1}</span><div className="min-w-0 flex-1"><p className="font-display text-[12px] font-extrabold uppercase leading-4 text-foreground">BONO #{index + 1} — {title}</p><p className="mt-0.5 text-[11px] font-bold text-primary">Valor: {value}</p></div></article>)}</div></div></Section>

        <Section className="border-y border-border/60"><div className="rounded-3xl border border-primary/40 bg-card p-5 text-center shadow-[0_0_50px_-24px_var(--primary)] sm:p-8"><p className="font-display text-xl font-extrabold uppercase text-primary sm:text-2xl">Valor de los bonos <strong className="ml-1 line-through">$142</strong></p><p className="mt-3 font-display text-sm font-extrabold uppercase text-foreground sm:text-base">Pero hoy no necesitas pagar $142 por ellos</p></div></Section>

        <Section><h2 className="text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">Personas que dejaron de sentirse solas</h2><div className="mt-8 space-y-4"><blockquote className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-3"><img src="/images/testimonial-1.jpeg" alt="Miguel, 68 años" className="size-12 shrink-0 rounded-full object-cover" /><p className="font-display text-sm font-bold text-primary">Miguel, 68 años (Santiago)</p></div><p className="mt-3 text-sm leading-6 text-muted-foreground">“Me quedaba perdido cuando ocurría algo nuevo. Una mancha roja me dejaba preocupado durante 3 días. Ahora le pregunto al Médico Virtual y recibo la orientación adecuada en ese mismo momento. Salí de aquel ciclo de pánico que estaba destruyendo mi bienestar.”</p><p className="mt-3 tracking-[0.2em] text-primary">⭐⭐⭐⭐⭐</p></blockquote><blockquote className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-3"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HmStFYb9GdXd3yFg4vdhPFWXJunVaM.png" alt="Carlos, 70 años" className="size-12 shrink-0 rounded-full object-cover" /><p className="font-display text-sm font-bold text-primary">Carlos, 70 años (Medellín)</p></div><p className="mt-3 text-sm leading-6 text-muted-foreground">“Me despertaba con miedo todas las noches, pensando que estaba empeorando. Ahora le pregunto al Médico Virtual si es normal o si debo preocuparme. El 90% de las veces es solo cosa de mi cabeza. Hoy puedo dormir tranquilo y eso lo cambió todo.”</p><p className="mt-3 tracking-[0.2em] text-primary">⭐⭐⭐⭐⭐</p></blockquote><blockquote className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-3"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-i4Gn4yxpkPrJN2JxmdNx4NcbfxvGWS.png" alt="Patricia, 58 años" className="size-12 shrink-0 rounded-full object-cover" /><p className="font-display text-sm font-bold text-primary">Patricia, 58 años (Quito)</p></div><p className="mt-3 text-sm leading-6 text-muted-foreground">“Compré el protocolo, pero tenía miedo de hacer algo mal y empeorar todo. Con el Médico Virtual respondiendo mis dudas al instante, gané mucha confianza. Hice los ejercicios correctamente y ahora salgo de casa tranquila. Lo que cambió fue la seguridad.”</p><p className="mt-3 tracking-[0.2em] text-primary">⭐⭐⭐⭐⭐</p></blockquote></div></Section>

        <Section className="border-y border-border/60"><div className="mt-5 rounded-2xl border border-warning/40 bg-warning/10 p-5 text-center"><p className="font-display text-lg font-extrabold uppercase">Esta condición especial está disponible únicamente en esta página.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Si sales ahora, no podemos garantizar el mismo precio, la misma disponibilidad ni una nueva incorporación inmediata.</p></div></Section>

        <Section><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">¿Cuánto vale tener un Médico Virtual que te entiende de por vida?</h2><div className="mt-8 grid gap-3">{['Evaluación Inicial Inteligente', 'Mapa + Checklist Diario', 'NeuroAssist 24h', 'Detector de Señales de Alerta', 'Análisis Visual con IA'].map((item) => <div key={item} className="flex items-start gap-3 rounded-xl border border-border bg-card p-4 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-primary" /><span className="font-semibold">{item}</span></div>)}</div><div className="mx-auto mt-9 max-w-md rounded-3xl border border-primary/40 bg-card p-6 text-center shadow-[0_0_45px_-20px_var(--primary)]"><p className="text-sm text-muted-foreground line-through">Valor total estimado · US$1.497</p><p className="mt-2 text-sm text-muted-foreground line-through">Precio normal · US$997</p><p className="mt-2 text-sm text-muted-foreground line-through">Precio de incorporación · US$697</p><p className="mt-6 font-display text-xs font-bold uppercase tracking-[0.2em] text-primary">Hoy después de tu compra</p><p className="mt-1 font-display text-6xl font-extrabold">US$97</p><p className="mt-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">Pago único · Acceso de por vida</p><PrimaryCta>Quiero mi Médico Virtual de por vida — US$97</PrimaryCta></div></Section>

        <Section><div className="rounded-3xl border-2 border-warning/40 bg-card p-6 text-center shadow-[0_0_50px_-25px_var(--warning)] sm:p-10"><img src="/images/garantia-7-dias.png" alt="Sello dorado de garantía de 7 días" className="mx-auto size-48 object-contain sm:size-60" /><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Garantía de satisfacción de 7 días</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-6 text-muted-foreground">Si por cualquier razón no estás completamente satisfecho con tu Médico Virtual, recibirás un reembolso del 100% sin preguntas. Tú te quedas con todo el acceso. Cero costo, cero complicaciones.</p><div className="mt-6 grid gap-2 text-left text-sm"><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> Funciona o no pagas nada.</p><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> Tú te quedas con todo el contenido.</p><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> El riesgo es 100% nuestro.</p></div></div></Section>

        <Section><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">La pieza que faltaba en tu proceso</h2><div className="mt-7 space-y-4 text-sm leading-6 text-muted-foreground"><p>¿Quién está contigo a las 3 de la mañana cuando aparece una duda? ¿Quién te dice si estás en el camino correcto o si algo es grave? ¿Quién te quita el miedo de estar solo en esto?</p><p className="font-display font-extrabold uppercase text-primary">Tu Médico Virtual 24H es la pieza que faltaba.</p><p>No es reemplazar lo que ya tienes. Es tener a alguien observando tu evolución específica todos los días. Es la diferencia entre esperar mejorar y saber que estás mejorando.</p></div><PrimaryCta>Quiero mi Médico Virtual 24H — US$97</PrimaryCta></Section>

        <Section><h2 className="mt-3 text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">Preguntas frecuentes</h2><div className="mt-8 space-y-3">{faqs.map(([question, answer]) => <details key={question} className="group overflow-hidden rounded-2xl border border-border bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3.5 font-display text-[13px] font-bold uppercase leading-5 sm:px-5 sm:py-4 sm:text-sm"><span>{question}</span><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary transition-transform group-open:rotate-180"><ChevronDown className="size-4" /></span></summary><p className="border-t border-border px-4 pb-4 pt-3 text-[13px] leading-5 text-muted-foreground sm:px-5 sm:pb-5 sm:pt-4 sm:text-sm sm:leading-6">{answer}</p></details>)}</div></Section>

        <Section id="oferta" className="relative overflow-hidden bg-primary px-5 text-center text-primary-foreground"><AlertTriangle className="mx-auto size-8" /><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Ahora tienes dos opciones</h2><div className="mt-7 grid gap-3 text-left sm:grid-cols-2"><div className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5"><p className="font-display font-extrabold uppercase">Opción 1</p><p className="mt-3 text-sm leading-6 opacity-85">Cerrar esta página, quedarte únicamente con los protocolos y buscar entre varios materiales cada vez que surja una duda urgente.</p></div><div className="rounded-2xl bg-background p-5 text-foreground"><p className="font-display font-extrabold uppercase text-primary">Opción 2</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Recibir tu Médico Virtual 24H, consultar tus síntomas, registrar cambios y descubrir cuándo necesitas acudir a un profesional.</p></div></div><div className="mx-auto mt-8 max-w-md rounded-3xl bg-background p-6 text-left text-foreground"><p className="font-display text-xl font-extrabold uppercase">Tu Médico Virtual 24H</p><p className="mt-3 text-sm leading-6 text-muted-foreground">No otro protocolo. No otro ebook. Un punto de apoyo digital para que nunca te quedes sin saber qué hacer.</p><div className="mt-5 flex items-end justify-between border-t border-border pt-5"><span className="text-xs font-bold uppercase text-muted-foreground">Pago único</span><span className="font-display text-4xl font-extrabold text-primary">US$97</span></div><PrimaryCta scrollTo="pagina">Añadir ahora — US$97 <ArrowRight className="ml-2 inline size-4" /></PrimaryCta></div><p className="mx-auto mt-8 max-w-lg text-xs leading-5 opacity-80">Aviso importante: este programa tiene finalidad educativa y organizativa. El Médico Virtual no sustituye evaluación, diagnóstico, tratamiento, prescripción ni seguimiento de un médico. Ante síntomas graves, busca atención médica inmediata.</p></Section>
      </div>
      <footer className="bg-background px-5 py-10 text-center text-xs text-muted-foreground"><p>Pago seguro · Pago único · Garantía de satisfacción</p><p className="mt-3">© 2026 — Todos los derechos reservados.</p><p className="mx-auto mt-4 max-w-xl leading-5">Política de Privacidad · Términos y Condiciones · Política de Reembolso</p></footer>
    </main>
  </>
}
